//created on: 25 oct 2024
package reglas

//list any import classes here. // Aquí debemos poner todas las clases involucradas en las reglas
import dsi.mitologia.Ser;
import dsi.mitologia.Estados;
import dsi.mitologia.Objetos;

//declare any global variables here


rule "Si X mata a Y se queda con los objetos de Y"

    when
        //conditions
    	//Pues cuando se inserte el hecho de X mata a Y
    	$x : Ser();
    	$y : Ser();
    then
        //actions
        modify($x)
        {
        	$x.addAllObjeto($y.getTiene_objeto()); // Agregamos todos los objetos de Y en X
        }
        
        modify($y)
        {
       		$y.removeAllObjeto();	// Eliminamos todos los objetos de Y
       		$y.setTiene_condicion(new HashSet<Estados>(Estados.MUERTO));	// REVISAR
        }
        
        System.out.println($x.getTiene_nombre() + " ha matado y tomado los objetos de " + $y.getTiene_nombre()); // PA DEPURAR
        
end


rule "Si X apresa a Y se queda con los objetos de Y"

    when
        //conditions
    	//Pues cuando se inserte el hecho de X aprese a Y
    	$x : Ser()
    	$y : Ser()
    then
        //actions
        modify($x)
        {
        	$x.addAllObjeto($y.getTiene_objeto()); // Agregamos todos los objetos de Y en X
        }
        
        modify($y)
        {
       		$y.removeAllObjeto();	// Eliminamos todos los objetos de Y
       		$y.removeCondicion(Estados.LIBRE);
       		$y.addCondicion(Estados.APRESADO);
        }
        
        System.out.println($x.getTiene_nombre() + "ha apresado y tomado los objetos de " + $y.getTiene_nombre()); // PA DEPURAR
        
end


rule "Si X libera a Y entonces Y es libre"

    when
        //conditions
    	//Pues cuando se inserte el hecho de X libera a Y
    	$y : Ser(tiene_condicion == Estados.APRESADO);
    then
        //actions        
        modify($y)
        {
       		$y.removeCondicion(Estados.APRESADO);
       		$y.addCondicion(Estados.LIBRE);
        }
        
        System.out.println($x.getTiene_nombre() + " ha liberado a " + $y.getTiene_nombre()); // PA DEPURAR
        
end


rule "Si X mata a Y e Y tiene preso a Z entonces X libera a Z"

    when
        //conditions
    	//Pues cuando se inserte el hecho de X mata a Y y este el hecho de que Y apresa a Z
    	$x : Ser()
    	$y : Ser()
    	$z : Ser()
    then
        //actions
        modify($x)
        {
        	$x.addAllObjeto($y.getTiene_objeto()); // Agregamos todos los objetos de Y en X
        }
        
        modify($y)
        {
       		$y.removeAllObjeto();	// Eliminamos todos los objetos de Y
       		$y.setTiene_condicion(new HashSet<Estados>(Estados.MUERTO));	// REVISAR
        }
        
        modify($z)
        {
        	$z.removeCondicion(Estados.APRESADO);
       		$z.addCondicion(Estados.LIBRE);
        }
        
        //TODO: No sé si se podría hacer esto
        //insert(X libera a Z) //Es decir no sé si aquí se pueden insertar hechos como tal
        
        System.out.println($x.getTiene_nombre() + " ha matado y tomado los objetos de " + $y.getTiene_nombre() + "y ha liberado a " + $z.getTiene_nombre()); // PA DEPURAR
        
end


rule "Si X roba a Y entonces X se queda con todos los objetos de Y"

    when
        //conditions
    	//Pues cuando se inserte el hecho de X roba a Y
    	$x : Ser()
    	$y : Ser()
    then
        //actions
        modify($x)
        {
        	$x.addAllObjeto($y.getTiene_objeto()); // Agregamos todos los objetos de Y en X
        }
        
        modify($y)
        {
       		$y.removeAllObjeto();	// Eliminamos todos los objetos de Y
        }
        
        System.out.println($x.getTiene_nombre() + " ha robado " + $y.getTiene_nombre()); // PA DEPURAR
        
end


rule "Si X roba a Y el objeto Z entonces X se queda con Z"

    when
        //conditions
    	//Pues cuando se inserte el hecho de X roba a Y
    	$x : Ser()
    	$y : Ser()
    	$z : Objetos()
    then
        //actions
        modify($x)
        {
        	$x.addObjeto($z); // Agregamos todos los objetos de Y en X
        }
        
        modify($y)
        {
       		$y.removeObjeto($z);	// Eliminamos el objeto Z de Y
        }
        
        System.out.println($x.getTiene_nombre() + " ha robado a " + $y.getTiene_nombre() + " el objeto " $z.getTiene_nombre()); // PA DEPURAR
        
end


rule "Your First Rule"

    when
        //conditions
    then
        //actions

end

rule "Your Second Rule"
    //include attributes such as "salience" here...
    when
        //conditions
    then
        //actions

end
